Repository russ-money/subterra, pull requests merged in 2024-08, with the labels that each got.

#1 First set of map improvements
  _maps/map_files/blackstone/blackstone.dmm
  _maps/map_files/oldtown/oldtown.dmm
  code/game/objects/structures/roguetown/wildlife_spawner.dm
  roguetown.dme
Labels: Mapping

#12 New crop sprites for the placeholders.
  icons/roguetown/items/produce.dmi
  icons/roguetown/misc/crops.dmi
Labels: Spriting

#14 new ending credits screen
  icons/fullblack.dmi
Labels: Spriting

#19 Adds 4 Druid spawns to blackstone.dmm
  _maps/map_files/blackstone/blackstone.dmm
Labels: Mapping

#22 Minor verbs/adminverbs tweaks
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/preferences.dm
  code/_onclick/hud/ghost.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/playerquality.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mob/mob_movement.dm
  icons/mob/screen_ghost.dmi
  interface/interface.dm
Labels: Spriting

#27 Lockpicks and Lockpicking [StoneKeep Port]
  code/game/objects/items.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/mineral_doors.dm
  code/modules/antagonists/roguetown/villain/bandit.dm
  code/modules/antagonists/roguetown/villain/maniac/maniac.dm
  code/modules/cargo/packsrogue/tools.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelt.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelthand.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/nakedandafraid.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/special/torso.dm
  code/modules/jobs/job_types/roguetown/courtier/jester.dm
  code/modules/jobs/job_types/roguetown/mercenaries/desertrider.dm
  code/modules/jobs/job_types/roguetown/mercenaries/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/peasants/beggar.dm
  code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
  code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/_anvil_recipe.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  icons/roguetown/items/lockpicks.dmi
  sound/items/pickbad.ogg
  sound/items/pickbreak.ogg
  sound/items/pickgood1.ogg
  sound/items/pickgood2.ogg
Labels: Spriting, Balance

#28 melt people again
  _maps/map_files/blackstone/blackstone.dmm
  code/game/objects/structures/roguetown/redstone.dm
Labels: Mapping

#35 Removes Grime And Fecal Filters
  code/_onclick/hud/generic_dextrous.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  icons/grain.dmi
  interface/interface.dm
Labels: Spriting

#36 Replaces a few backgrounds
  icons/default_title.dmi
  icons/fullblack.dmi
  icons/gameover.dmi
Labels: Spriting

#40 Tiefling Maids/Butlers
  code/modules/jobs/job_types/roguetown/courtier/butler.dm
Labels: Balance
