Repository russ-money/subterra, pull requests merged in 2024-09, with the labels that each got.

#46 Emotes in runechat
  code/__DEFINES/say.dm
  code/__HELPERS/_logging.dm
  code/datums/chatmessage.dm
  code/datums/emotes.dm
  code/modules/mob/mob.dm
  icons/UI_Icons/chat/chat_icons.dmi
Labels: Spriting

#49 Updates Adventurer Spawn Locations
  _maps/map_files/blackstone/blackstone.dmm
Labels: Mapping

#50 Arcane Spellcasting Update
  code/modules/antagonists/roguetown/villain/peasantrebel.dm
  code/modules/antagonists/roguetown/villain/werewolf/werewolf_spells.dm
  code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/sorceress.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
  code/modules/jobs/job_types/roguetown/nobility/lady.dm
  code/modules/jobs/job_types/roguetown/nobility/lord.dm
  code/modules/jobs/job_types/roguetown/nobility/sheriff.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/spells/roguetown/_roguetown.dm
  code/modules/spells/roguetown/arcane.dm
  code/modules/spells/roguetown/arcane/blindness.dm
  code/modules/spells/roguetown/arcane/blink.dm
  code/modules/spells/roguetown/arcane/fetch.dm
  code/modules/spells/roguetown/arcane/fireball.dm
  code/modules/spells/roguetown/arcane/ignite.dm
  code/modules/spells/roguetown/arcane/invisibility.dm
  code/modules/spells/roguetown/arcane/lightning.dm
  code/modules/spells/roguetown/arcane/smokescreen.dm
  code/modules/spells/roguetown/arcane/swap.dm
  code/modules/spells/roguetown/arcane/telepathy.dm
  code/modules/spells/roguetown/other/grant_title.dm
  code/modules/spells/roguetown/other/jester.dm
  code/modules/spells/roguetown/other/recruiting.dm
  icons/mob/actions/roguespells.dmi
  icons/mob/actions/roguespellsbackup.dmi
  roguetown.dme
Labels: Spriting, Balance
